---
- name: 部署基础环境
  hosts: all
  become: yes
  roles:
    - common
  tags: common

- name: 部署数据库和监控栈
  hosts: db_monitor
  become: yes
  roles:
    - postgres
    - prometheus
    - grafana
  tags: db_monitor

- name: 部署web应用栈
  hosts: web
  become: yes
  roles:
    - app
    - nginx
  tags: web

- name: 验证部署情况
  hosts: all
  become: yes
  tasks: 
    - name: 检查docker服务状态
      command: docker ps
      register: docker_ps
      changed_when: false

    - name: 显示docker状态服务
      debug:
        var: docker_ps.stdout_lines
